server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_hotel?useSSL=false
    username: root
    password: 403630
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    port: 5672
    host: 47.109.59.20
    virtual-host: / # 虚拟主机
    username: cm # 用户名
    password: 403630 # 密码
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo

